Nesse notebook veremos melhor cada um dos Data Types:

# Vetores:

- Quando escrevemos um único valor em R, esse valor é um vetor unitário.
- Podemos criar vetores de sequências:

In [1]:
s <- 1:10
print(s)

 [1]  1  2  3  4  5  6  7  8  9 10


In [2]:
s2 <- 2.5:10.5
print(s2)

[1]  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5


In [4]:
s3 <- 5.3:8.8
print(s3)

[1] 5.3 6.3 7.3 8.3


- Podemos usar a função $\textbf{seq()}$ para criar vetores e a função $\textbf{c()}$, que vimos anteriormente.

In [6]:
s4 <- 5:9
print(s4)
print(class(s4))
s4 <- seq(5, 9, by = 0.4)
print(s4)
print(class(s4))

[1] 5 6 7 8 9
[1] "integer"
 [1] 5.0 5.4 5.8 6.2 6.6 7.0 7.4 7.8 8.2 8.6 9.0
[1] "numeric"


- Podemos devolver os elementos na posição desejada.

In [7]:
t <- c("Sun","Mon","Tue","Wed","Thurs","Fri","Sat") #Dizendo explicitamente a posição pelo número dela
u <- t[c(2,3,6)]
print(u)

[1] "Mon" "Tue" "Fri"


In [8]:
v <- t[c(TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE)] #Usando o booleano para marcar as que queremos
print(v)

[1] "Sun" "Fri"


- Podemos devolver o vetor retirando alguns elementos dele.

In [15]:
t <- c("Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro", "Dezembro")
x <- t[c(-2,-5,-8,-10,-12)]
print(x)

[1] "Janeiro"  "Março"    "Abril"    "Junho"    "Julho"    "Setembro" "Novembro"


- Podemos ordenar com a função $\textbf{sort()}$.

In [9]:
v <- c(3,8,4,5,0,11, -9, 304)

# Ordenando.
sort.result <- sort(v, decreasing = FALSE)
print(sort.result)

# Ordenando na ordem decrescente.
revsort.result <- sort(v, decreasing = TRUE)
print(revsort.result)

# Ordenando strings pela ordem alfabética.
v <- c("Amarelo","Azul","Branco","Rosa","Roxo","Vermelho","Verde","Bege")
sort.result <- sort(v)
print(sort.result)

# Ordenando strings pela ordem inversa da alfabética.
revsort.result <- sort(v, decreasing = TRUE)
print(revsort.result)

[1]  -9   0   3   4   5   8  11 304
[1] 304  11   8   5   4   3   0  -9
[1] "Amarelo"  "Azul"     "Bege"     "Branco"   "Rosa"     "Roxo"     "Verde"   
[8] "Vermelho"
[1] "Vermelho" "Verde"    "Roxo"     "Rosa"     "Branco"   "Bege"     "Azul"    
[8] "Amarelo" 


# Listas:

- Nomeando os elementos da lista

In [10]:
# Criando uma lista que contém um vetor, uma matriz e uma lista:
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),
   list("green",12.3))

# Nomeando os elementos:
names(list_data) <- c("1º_trimeste", "Matrix", "outra_lista")

print(list_data)

$`1º_trimeste`
[1] "Jan" "Feb" "Mar"

$Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$outra_lista
$outra_lista[[1]]
[1] "green"

$outra_lista[[2]]
[1] 12.3




- Acessando os elementos de uma lista:

In [11]:
print(list_data[1])


$`1º_trimeste`
[1] "Jan" "Feb" "Mar"



In [12]:
print(list_data[2])

$Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8



In [13]:
print(list_data[3])


$outra_lista
$outra_lista[[1]]
[1] "green"

$outra_lista[[2]]
[1] 12.3




- Criando novos elementos:

In [14]:
list_data[4] <- "Novo elemento"
print(list_data)

$`1º_trimeste`
[1] "Jan" "Feb" "Mar"

$Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$outra_lista
$outra_lista[[1]]
[1] "green"

$outra_lista[[2]]
[1] 12.3


[[4]]
[1] "Novo elemento"



- Removendo elementos:

In [15]:
list_data[2] <- NULL
print(list_data)

$`1º_trimeste`
[1] "Jan" "Feb" "Mar"

$outra_lista
$outra_lista[[1]]
[1] "green"

$outra_lista[[2]]
[1] 12.3


[[3]]
[1] "Novo elemento"



- Alterando elementos:

In [16]:
list_data[2] <- "Aqui era o lugar da lista"
print(list_data)

$`1º_trimeste`
[1] "Jan" "Feb" "Mar"

$outra_lista
[1] "Aqui era o lugar da lista"

[[3]]
[1] "Novo elemento"



- Juntando listas:

In [19]:
lista1 <- list(1,2,3)
lista2 <- list(4,5,6)
lista3 <-c(lista1,lista2)
print(lista3)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] 6



 - Podemos transformar uma lista em um vetor usando a função $\textbf{unlist()}$:

In [21]:
print(lista1)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3



In [22]:
v1 <- unlist(lista1)
print(v1)

[1] 1 2 3


In [23]:
print(lista1)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3



In [24]:
v2 <- unlist(lista2)
print(v2)

[1] 4 5 6


In [25]:
print(lista2)

[[1]]
[1] 4

[[2]]
[1] 5

[[3]]
[1] 6



# Matriz:

- Podemos defini-la por linhas

In [55]:
M_l <- matrix(c(3:14), nrow = 4, byrow = TRUE)
print(M_l)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


- Podemos defini-las por coluna

In [56]:
M_c <- matrix(c(3:14), nrow = 4, byrow = FALSE)
print(M_c)

     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14


- Podemos nomear suas colunas e suas linhas

In [59]:
nome_linhas = c("linha1", "linha2", "linha3", "linha4")
nome_colunas = c("col1", "col2", "col3")
M_nomeada <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(nome_linhas, nome_colunas))
print(M_nomeada)

       col1 col2 col3
linha1    3    4    5
linha2    6    7    8
linha3    9   10   11
linha4   12   13   14


- Acessando coluna

In [61]:
print(M_nomeada[,3]) #Coluna 3

linha1 linha2 linha3 linha4 
     5      8     11     14 


- Acessando linha

In [60]:
print(M_nomeada[2,]) #Linha 2

col1 col2 col3 
   6    7    8 


- Acessando elemento

In [62]:
print(M_nomeada[2,3]) # Elemento da coluna 3 e linha 2

[1] 8


- Adição de matrizes

In [2]:
matrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
matrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix1)
print(matrix2)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6
     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4


In [4]:
soma_matriz <- matrix1+matrix2
print(soma_matriz)

     [,1] [,2] [,3]
[1,]    8   -1    5
[2,]   11   13   10


- Subtração de matrizes

In [5]:
subtração_matriz <- matrix1 - matrix2
print(subtração_matriz)

     [,1] [,2] [,3]
[1,]   -2   -1   -1
[2,]    7   -5    2


- Multiplicação dos elementos d de duas matrizes:

In [8]:
multiplicação <- matrix1 * matrix2
print(multiplicação)

     [,1] [,2] [,3]
[1,]   15    0    6
[2,]   18   36   24


- Divisão dos elementos da matriz pelo elemeto correspondente de outra matriz

In [7]:
divisão <- matrix1 / matrix2
print(divisão)

     [,1]      [,2]      [,3]
[1,]  0.6      -Inf 0.6666667
[2,]  4.5 0.4444444 1.5000000


# Arrays:

Arrays são criados usando a função $\textbf{array()}$. Tomam os vetores como input e usam os valores no $\textbf{dim}$ como parâmetros para criar o array.

In [9]:
# Criando os vetores
vetor_1 <- c(5,9,3)
vetor_2 <- c(10,11,12,13,14,15)

In [12]:
# Criando o array de dimensão (3,3,2), isso é, duas matrizes 3x3
meu_array <- array(c(vetor_1,vetor_2),dim = c(3,3,2))
print(meu_array)

, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 2

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15



- Podemos nomear as matrizes, suas linhas e suas colunas

In [13]:
colunas <- c("C1","C2","C3")
linhas <- c("L1","L2","L3")
matrizes <- c("Matriz_1","Matriz_2")
array_nomeado <- array(c(vetor_1,vetor_2),dim = c(3,3,2),dimnames = list(linhas,colunas,
   matrizes))
print(array_nomeado)

, , Matriz_1

   C1 C2 C3
L1  5 10 13
L2  9 11 14
L3  3 12 15

, , Matriz_2

   C1 C2 C3
L1  5 10 13
L2  9 11 14
L3  3 12 15



- Podemos acessar os elementos
                [ linha, coluna, matriz]

In [14]:
# A primeira matriz
print(array_nomeado[,,1])

   C1 C2 C3
L1  5 10 13
L2  9 11 14
L3  3 12 15


In [15]:
# A segunda matriz
print(array_nomeado[,,2])

   C1 C2 C3
L1  5 10 13
L2  9 11 14
L3  3 12 15


In [16]:
# A segunda linha da primeira matriz
print(array_nomeado[2,,1])

C1 C2 C3 
 9 11 14 


In [17]:
# Elemento da terceira linha da primeira coluna da segunda matriz
print(array_nomeado[3,1,2])

[1] 3


- Podemos manipular o array 

In [24]:
vetor_3 <- c(9,1,0)
vetor_4 <- c(6,0,11,3,14,1,2,6,9)
array_2 <- array(c(vetor_3,vetor_4),dim = c(3,3,2))
matriz1 <- meu_array[,,1]
matriz2 <- array_2[,,2]

In [25]:
print(array_2)

, , 1

     [,1] [,2] [,3]
[1,]    9    6    3
[2,]    1    0   14
[3,]    0   11    1

, , 2

     [,1] [,2] [,3]
[1,]    2    9    6
[2,]    6    1    0
[3,]    9    0   11



In [26]:
print(meu_array)

, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 2

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15



In [27]:
print(matriz1)

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15


In [28]:
print(matriz2)

     [,1] [,2] [,3]
[1,]    2    9    6
[2,]    6    1    0
[3,]    9    0   11


- Podemos fazer cálculos em todos os elementos de uma matriz usando a função $\textbf{apply ()}$.

                apply(array, data set usado, função)

In [31]:
# Calcularemos a soma das linhas de todo o array
soma_linhas <- apply(array_2, c(1), sum)
print(soma_linhas)

[1] 35 22 32


In [33]:
mean_linhas <- apply(array_2, c(1), mean)
print(mean_linhas)

[1] 5.833333 3.666667 5.333333


# Factors

Factors são usados para categorizar os dados e armazenar os níveis.


In [34]:
data <- c("East","West","East","North","North","East","West","West","West","East","North")
print(data)
print(is.factor(data))


 [1] "East"  "West"  "East"  "North" "North" "East"  "West"  "West"  "West" 
[10] "East"  "North"
[1] FALSE


In [35]:
factor_data <- factor(data)
print(factor_data)
print(is.factor(factor_data))

 [1] East  West  East  North North East  West  West  West  East  North
Levels: East North West
[1] TRUE


- Podemos usar Factors dentro de Data Frames

Quando criamos um Data Frame com uma das colunas com texto (strings), R trata essa coluna como factor.

In [37]:
# Criando os vetores para a tabela
height <- c(132,151,162,139,166,147,122)
weight <- c(48,49,66,53,67,52,40)
gender <- c("male","male","female","female","male","female","male")

# Criando o data frame
input_data <- data.frame(height,weight,gender)
print(input_data)

  height weight gender
1    132     48   male
2    151     49   male
3    162     66 female
4    139     53 female
5    166     67   male
6    147     52 female
7    122     40   male


In [38]:
print(is.factor(input_data$gender))

[1] TRUE


In [40]:
print(input_data$gender)

[1] male   male   female female male   female male  
Levels: female male


- Podemos trocar a ordem dos níveis


In [42]:
print(factor_data)
nova_ordem <- factor(factor_data,levels = c("East","West","North"))
print(nova_ordem)

 [1] East  West  East  North North East  West  West  West  East  North
Levels: East North West
 [1] East  West  East  North North East  West  West  West  East  North
Levels: East West North


- Podemos gerar níveis em factors

Usamos a função $\textbf{gl()}$ dessa forma:

                gl(n, k, labels)
                
onde n é a quantidade de níveis, k é o número de vezes que queremos que cada nível seja repetido e labels é o vetor dos rótulos dado como resultado do factor.


In [43]:
v <- gl(3, 4, labels = c("Tampa", "Seattle","Boston"))
print(v)

 [1] Tampa   Tampa   Tampa   Tampa   Seattle Seattle Seattle Seattle Boston 
[10] Boston  Boston  Boston 
Levels: Tampa Seattle Boston


# Data Frames:

Os dataframes possuem as seguintes características:
- As colunas devem ter nomes;
- Nome de linha deve ser único;
- O dado armazenado pode ser numérico, factor ou string;
- Toda coluna precisa conter o mesmo nómero de itens.

In [45]:
emp.data <- data.frame(
   emp_id = c (1:5), 
   emp_name = c("Rick","Dan","Michelle","Ryan","Gary"),
   salary = c(623.3,515.2,611.0,729.0,843.25), 
   
   start_date = as.Date(c("2012-01-01", "2013-09-23", "2014-11-15", "2014-05-11",
      "2015-03-27")),
   stringsAsFactors = FALSE
)

print(emp.data) 

  emp_id emp_name salary start_date
1      1     Rick 623.30 2012-01-01
2      2      Dan 515.20 2013-09-23
3      3 Michelle 611.00 2014-11-15
4      4     Ryan 729.00 2014-05-11
5      5     Gary 843.25 2015-03-27


- Podemos ver a estrutura do Data Frame através da função $\textbf{str()}$

In [47]:
# Criando uma nova tabela
emp.data <- data.frame(
   emp_id = c (1:5), 
   emp_name = c("Rick","Dan","Michelle","Ryan","Gary"),
   salary = c(623.3,515.2,611.0,729.0,843.25), 
   
   start_date = as.Date(c("2012-01-01", "2013-09-23", "2014-11-15", "2014-05-11",
      "2015-03-27")),
   stringsAsFactors = FALSE
)
# Vendo a estrutura da tabela
str(emp.data)

'data.frame':	5 obs. of  4 variables:
 $ emp_id    : int  1 2 3 4 5
 $ emp_name  : chr  "Rick" "Dan" "Michelle" "Ryan" ...
 $ salary    : num  623 515 611 729 843
 $ start_date: Date, format: "2012-01-01" "2013-09-23" ...


- O resumo estatístico e a natureza dos dados podem ser obtidos através da aplicação da função  $\textbf{summary()}$

In [48]:
summary(emp.data)

     emp_id    emp_name             salary        start_date        
 Min.   :1   Length:5           Min.   :515.2   Min.   :2012-01-01  
 1st Qu.:2   Class :character   1st Qu.:611.0   1st Qu.:2013-09-23  
 Median :3   Mode  :character   Median :623.3   Median :2014-05-11  
 Mean   :3                      Mean   :664.4   Mean   :2014-01-14  
 3rd Qu.:4                      3rd Qu.:729.0   3rd Qu.:2014-11-15  
 Max.   :5                      Max.   :843.2   Max.   :2015-03-27  

- Podemos extrair os dados de alguma coluna

In [51]:
# Usa-se $ para chamar a coluna
nome_e_salario <- data.frame(emp.data$emp_name,emp.data$salary) 
print(nome_e_salario)

  emp.data.emp_name emp.data.salary
1              Rick          623.30
2               Dan          515.20
3          Michelle          611.00
4              Ryan          729.00
5              Gary          843.25


- Podemos extrair os dados de alguma linha 

In [53]:
Rick_e_Dan <- emp.data[1:2,]
print(Rick_e_Dan)

  emp_id emp_name salary start_date
1      1     Rick  623.3 2012-01-01
2      2      Dan  515.2 2013-09-23


- Podemos extrair combinações de linhas e colunas

In [54]:
#linhas 3 e 5 com as colunas 2 e 4
result <- emp.data[c(3,5),c(2,4)]  
print(result)

  emp_name start_date
3 Michelle 2014-11-15
5     Gary 2015-03-27


- Podemos adicionar colunas

In [55]:
emp.data$dept <- c("IT","Operations","IT","HR","Finance")
v <- emp.data
print(v)

  emp_id emp_name salary start_date       dept
1      1     Rick 623.30 2012-01-01         IT
2      2      Dan 515.20 2013-09-23 Operations
3      3 Michelle 611.00 2014-11-15         IT
4      4     Ryan 729.00 2014-05-11         HR
5      5     Gary 843.25 2015-03-27    Finance


- Podemos adicionar linhas


Para adicionar mais linhas permanentemente a uma tabela existente, precisamos inserir as novas linhas na mesma estrutura da tabela de dados existente e usar a função $\textbf{rbind ()}$ para fazer o merge das duas.

In [57]:
# Criando a tabela com os novos dados que desejo adicionar
emp.newdata <- 	data.frame(
   emp_id = c (6:8), 
   emp_name = c("Kate","Anne","Liza"),
   salary = c(578.0,722.5,632.8), 
   start_date = as.Date(c("2013-05-21","2013-07-30","2014-06-17")),
   dept = c("IT","Operations","Fianance"),
   stringsAsFactors = FALSE
)

# Fazendo o merge das duas tabelas
emp.completa <- rbind(emp.data,emp.newdata)
print(emp.completa)

  emp_id emp_name salary start_date       dept
1      1     Rick 623.30 2012-01-01         IT
2      2      Dan 515.20 2013-09-23 Operations
3      3 Michelle 611.00 2014-11-15         IT
4      4     Ryan 729.00 2014-05-11         HR
5      5     Gary 843.25 2015-03-27    Finance
6      6     Kate 578.00 2013-05-21         IT
7      7     Anne 722.50 2013-07-30 Operations
8      8     Liza 632.80 2014-06-17   Fianance
