In [1]:
import numpy as np

In [31]:
a = np.array([[1,2.],[4,3]])
b = np.array([[1,9],[7,5]])

In [32]:
a

array([[1., 2.],
       [4., 3.]])

In [33]:
b

array([[1, 9],
       [7, 5]])

In [34]:
A = np.matrix(a)
B = np.matrix(b)

In [35]:
a * b

array([[ 1., 18.],
       [28., 15.]])

In [36]:
A * B

matrix([[15., 19.],
        [25., 51.]])

In [37]:
a.shape

(2, 2)

In [38]:
a.dtype

dtype('float64')

In [25]:
c = np.arange(40).reshape(2,2,2,5)
print(c.shape)
print()
print(c)

(2, 2, 2, 5)

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]]


 [[[20 21 22 23 24]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [35 36 37 38 39]]]]


In [29]:
c.dtype

dtype('int64')